### ISSUE TITLE
Use an error in the ionic3

### ISSUE THREAD

**Issue by shanghen** [emin93/ng-qrcode#2] opened 2017-07-05 09:25 UTC
**version**
angular：4.1.3；
ionic：3.5.0；
ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'value' since it isn't a known property of 'qr-code'.
1. If 'qr-code' is an Angular component and it has 'value' input, then verify that it is part of this module.
2. If 'qr-code' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
 
   <qr-code [ERROR ->][value]="link" [size]="150"></qr-code>

**Comment by emin93** [comment] 2017-07-05 09:32
Thanks for creating issue. Are you sure you didn't forget to import the QRCodeModule in your NgModule? If that also doesn't help, please post a repository to reproduce the issue.

**Comment by shanghen** [comment] 2017-07-05 10:05
Excuse me, I found the reason when I tried to reproduce
This error occurs when lazy loading is used in ionic3

**Comment by emin93** [comment] 2017-07-05 11:21
I also do lazy loading in Ionic. You will have to import the QRCodeModule in every lazy loaded module where you need it. Hope this helps.

**Comment by emin93** [comment] 2017-07-05 12:20
I will close this issue for now because i think this doesn't seem to be related with this module.

**Closed by emin93** 2017-07-05 12:20 UTC
Labels: need info, question
